name: payuung_clone
description: "A clone of Payuung Pribadi App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: ^0.20.5                         # Flutter hooks for functional widget composition.
  auto_route: ^9.2.2                             # A Flutter routing library that generates route code.
  flutter_bloc: ^8.1.6                           # Implements the BLoC pattern for state management in Flutter.
  freezed: ^2.5.7                                # Code generation for immutable classes in Dart/Flutter.
  freezed_annotation: ^2.4.4                     # Annotations for the Freezed library.
  get: ^4.6.6                                    # Simple state management for Flutter.
  get_it: ^7.7.0                                 # A service locator for Flutter.
  json_annotation: ^4.9.0                        # Code generation for JSON serialization/deserialization.
  flutter_svg: ^2.0.10+1                            # Render SVG files in Flutter apps.
  analyzer: ^6.7.0                               # A versatile package for efficient code analysis in Flutter projects.
  pull_to_refresh: ^2.0.0                        # Add pull-to-refresh functionality to Flutter views.
  injectable: ^2.4.4                             # Dependency injection for Flutter and Dart.
  intl: ^0.19.0                                  # Internationalization and localization for Flutter.
  easy_stepper: ^0.8.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  auto_route_generator: ^9.0.0               # A code generator for AutoRoute, a Flutter routing library.
  injectable_generator: ^2.6.2               # A code generator for the Injectable dependency injection library in Flutter.
  json_serializable: ^6.8.0                 # A code generation library for JSON serialization and deserialization in Dart/Flutter.
  build_runner: ^2.4.12                       # A build system for generating Dart code in your Flutter project.

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
